import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    AUTH_GOOGLE_ID: z.string().optional(),
    AUTH_GOOGLE_SECRET: z.string().optional(),
    AUTH_GITHUB_ID: z.string().optional(),
    AUTH_GITHUB_SECRET: z.string().optional(),
    AUTH_SECRET: z.string(),
    AUTH_MICROSOFT_CLIENT_ID: z.string().optional(),
    AUTH_MICROSOFT_CLIENT_SECRET: z.string().optional(),
    DATABASE_URL: z.string().min(1),
    OPENAI_API_KEY: z.string().optional(),
    GROQ_API_KEY: z.string().optional(),
    RESEND_API_KEY: z.string(),
    UPSTASH_REDIS_REST_URL: z.string().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    UPSTASH_VECTOR_REST_URL: z.string().optional(),
    UPSTASH_VECTOR_REST_TOKEN: z.string().optional(),
    TRIGGER_SECRET_KEY: z.string().optional(),
    TRIGGER_API_KEY: z.string().optional(),
    TRIGGER_API_URL: z.string().optional(),
    REVALIDATION_SECRET: z.string(),
    VERCEL_ACCESS_TOKEN: z.string().optional(),
    VERCEL_TEAM_ID: z.string().optional(),
    VERCEL_PROJECT_ID: z.string().optional(),
    TRUST_PORTAL_PROJECT_ID: z.string().optional(),
    NODE_ENV: z.string().optional(),
    APP_AWS_ENDPOINT: z.string().optional(),
    APP_AWS_ACCESS_KEY_ID: z.string().optional(),
    APP_AWS_SECRET_ACCESS_KEY: z.string().optional(),
    APP_AWS_REGION: z.string().optional(),
    APP_AWS_BUCKET_NAME: z.string().optional(),
    APP_AWS_QUESTIONNAIRE_UPLOAD_BUCKET: z.string().optional(),
    APP_AWS_KNOWLEDGE_BASE_BUCKET: z.string().optional(),
    APP_AWS_ORG_ASSETS_BUCKET: z.string().optional(),
    NEXT_PUBLIC_PORTAL_URL: z.string(),
    FIRECRAWL_API_KEY: z.string().optional(),
    FLEET_URL: z.string().optional(),
    FLEET_TOKEN: z.string().optional(),
    DUB_API_KEY: z.string().optional(),
    DUB_REFER_URL: z.string().optional(),
    GA4_API_SECRET: z.string().optional(),
    GA4_MEASUREMENT_ID: z.string().optional(),
    LINKEDIN_CONVERSIONS_ACCESS_TOKEN: z.string().optional(),
    NOVU_API_KEY: z.string().optional(),
  },

  client: {
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
    NEXT_PUBLIC_IS_DUB_ENABLED: z.string().optional(),
    NEXT_PUBLIC_GTM_ID: z.string().optional(),
    NEXT_PUBLIC_LINKEDIN_PARTNER_ID: z.string().optional(),
    NEXT_PUBLIC_LINKEDIN_CONVERSION_ID: z.string().optional(),
    NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_LABEL: z.string().optional(),
    NEXT_PUBLIC_API_URL: z.string().optional(),
    NEXT_PUBLIC_BETTER_AUTH_URL: z.string().optional(),
    NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: z.string().optional(),
  },

  runtimeEnv: {
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID,
    AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_MICROSOFT_CLIENT_ID: process.env.AUTH_MICROSOFT_CLIENT_ID,
    AUTH_MICROSOFT_CLIENT_SECRET: process.env.AUTH_MICROSOFT_CLIENT_SECRET,
    DATABASE_URL: process.env.DATABASE_URL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    UPSTASH_VECTOR_REST_URL: process.env.UPSTASH_VECTOR_REST_URL,
    UPSTASH_VECTOR_REST_TOKEN: process.env.UPSTASH_VECTOR_REST_TOKEN,
    TRIGGER_SECRET_KEY: process.env.TRIGGER_SECRET_KEY,
    TRIGGER_API_KEY: process.env.TRIGGER_API_KEY,
    TRIGGER_API_URL: process.env.TRIGGER_API_URL,
    REVALIDATION_SECRET: process.env.REVALIDATION_SECRET,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    VERCEL_ACCESS_TOKEN: process.env.VERCEL_ACCESS_TOKEN,
    VERCEL_TEAM_ID: process.env.VERCEL_TEAM_ID,
    VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID,
    TRUST_PORTAL_PROJECT_ID: process.env.TRUST_PORTAL_PROJECT_ID,
    NODE_ENV: process.env.NODE_ENV,
    APP_AWS_ENDPOINT: process.env.APP_AWS_ENDPOINT,
    APP_AWS_ACCESS_KEY_ID: process.env.APP_AWS_ACCESS_KEY_ID,
    APP_AWS_SECRET_ACCESS_KEY: process.env.APP_AWS_SECRET_ACCESS_KEY,
    APP_AWS_REGION: process.env.APP_AWS_REGION,
    APP_AWS_BUCKET_NAME: process.env.APP_AWS_BUCKET_NAME,
    APP_AWS_QUESTIONNAIRE_UPLOAD_BUCKET: process.env.APP_AWS_QUESTIONNAIRE_UPLOAD_BUCKET,
    APP_AWS_KNOWLEDGE_BASE_BUCKET: process.env.APP_AWS_KNOWLEDGE_BASE_BUCKET,
    APP_AWS_ORG_ASSETS_BUCKET: process.env.APP_AWS_ORG_ASSETS_BUCKET,
    NEXT_PUBLIC_PORTAL_URL: process.env.NEXT_PUBLIC_PORTAL_URL,
    FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
    FLEET_URL: process.env.FLEET_URL,
    FLEET_TOKEN: process.env.FLEET_TOKEN,
    DUB_API_KEY: process.env.DUB_API_KEY,
    DUB_REFER_URL: process.env.DUB_REFER_URL,
    NEXT_PUBLIC_IS_DUB_ENABLED: process.env.NEXT_PUBLIC_IS_DUB_ENABLED,
    NEXT_PUBLIC_GTM_ID: process.env.NEXT_PUBLIC_GTM_ID,
    NEXT_PUBLIC_LINKEDIN_PARTNER_ID: process.env.NEXT_PUBLIC_LINKEDIN_PARTNER_ID,
    NEXT_PUBLIC_LINKEDIN_CONVERSION_ID: process.env.NEXT_PUBLIC_LINKEDIN_CONVERSION_ID,
    GA4_API_SECRET: process.env.GA4_API_SECRET,
    GA4_MEASUREMENT_ID: process.env.GA4_MEASUREMENT_ID,
    LINKEDIN_CONVERSIONS_ACCESS_TOKEN: process.env.LINKEDIN_CONVERSIONS_ACCESS_TOKEN,
    NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_LABEL: process.env.NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_LABEL,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_BETTER_AUTH_URL: process.env.NEXT_PUBLIC_BETTER_AUTH_URL,
    NOVU_API_KEY: process.env.NOVU_API_KEY,
    NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: process.env.NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER,
  },

  skipValidation: !!process.env.CI || !!process.env.SKIP_ENV_VALIDATION,
});
